productName = "sonusmix"
version = "0.1.0"
identifier = "sonusmix.app"

[build]
frontendDist = "../build"
devUrl = "http://localhost:1420"
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"

[[app.windows]]
title = "Sonusmix"
width = 800
height = 600

# [[app.security]]
# csp = null # null doesn't exist in TOML so we just leave this whole part out

[bundle]
active = true
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
