when:
  - event: [push, pull_request]
    branch: main

steps:
  - name: cargo check
    image: nixos/nix
    commands:
      - nix --extra-experimental-features 'nix-command flakes' develop .#minimal --command cargo check
