when:
    - event: tag
      ref: refs/tags/v*

steps:
    - name: build AppImage
      image: nixos/nix
      commands:
          - nix-channel --update
          - nix-shell --command "cargo make --disable-check-for-updates build-appimage"
    - name: publish
      image: woodpeckerci/plugin-release
      settings:
          files:
              - org.sonusmix.Sonusmix-${CI_COMMIT_TAG##v}.AppImage
          checksum: sha1
          title: "Version ${CI_COMMIT_TAG##v}"
          draft: true
          api_key:
              from_secret: GITEA_SECRET
